### PR TITLE
fix doubleclick server being buggy

### LINKED ISSUE #125: Double-clicking to connect hangs on 'Loading characters' if done too fast
**Steps to reproduce:**

1. Launch the client. Make sure 'public servers' is selected.

2. Double-click any server in the list. (Do not click the server beforehand!)

**Expected result:**
Connection should happen the same way it does when using the 'Connect' button.

**Actual result:**
Loading will inevitably hang on 'Loading characters'. Escape from this state requires the user to 'cancel' the loading process and attempt to connect again.

**Additional details:**
This seems to be linked to the server's player count being fetched, as if one selects the server beforehand and waits for the player count to populate before double-clicking, connection works as expected.

**Possible fix:**
While hacky, a hardcoded delay in the double-click function would likely solve this. Alternatively, (and much more cleanly,) making sure the player count has been fetched before actually connecting is also a likely solution.

### PR DESCRIPTION
**Pull request by scatterflower**
this is a bit of a hack, but so is the rest of ao2 :^)

this won't work with ao1.x servers but honestly who cares

a more in-depth rewrite of connection handling is honestly needed. another limitation of this PR is that it doesn't fix the problem of pressing "connect" before the player count shows up will mess things up. a more sane solution would be to totally separate the connection for fetching player count from actually connecting to the server. basically, lobby.cpp initiates a connection, and if someone connects to a server, that QTcpSocket is killed off, and a new one is used to connect to the server. another thing i noticed while looking through the code is the bizarre way in which send_server_packet() works. It takes a pointer to an AOPacket, and is always invoked with the param of a new AOPacket(). I guess omni thought it was Java. The pointer is deleted at the end of send_server_packet which is just unnecessary if proper RAII guidelines are followed.

fixes #125

### CODE REVIEW

**Comment by scatterflower** [comment]
honestly, anything that touches networkmanager.cpp needs to be nuked. a very significant rewrite is needed. a more sane way to handle this would be to create an abstract AOClient or something of the sorts. The problem is that courtroom.cpp is very deeply entangled with the code in packet_distribution.cpp.

if we make an AOClient class which exposes some signals, then appropriate slots in courtroom.cpp can be created and connected.
when we receive a packet, it can send a signal containing the packet formatted as a nice object with access to the headers and whatnot. the actual packet handler can be moved into courtroom.cpp, and rewritten in a prettier way (function pointers a la akashi?) that way, there is no `if (!courtroom_constructed)` nonsense, and the internal state of the courtroom object can begin to be isolated from the instance of AOApplication. The more these are decoupled, the more modularized it allows the code to become...

**Comment by scatterflower** [comment]
the amount of work to do this all *properly* is honestly quite sisyphean, and it is frankly more reasonable to just start from the ground up at a certain point. i am losing more and more hope every day that this project can continue on in its current form.

**Comment by scatterflower** [comment]
It just occurred to me that I should probably explain *why* this bug existed in the first place. Basically, all connections over the network are funneled through NetworkManager. This means there is only ever one active tcp socket at a time (two if you count the MS). When you click on a server once, that socket is opened, and the initial part of the handshake is performed (get decryptor, send HI, ID, get FL, get PN). When the function to connect to a server is invoked, it straight up sends an "askchaa". If this askchaa is sent before the rest of the handshake, it messes up the server connection, and everything goes haywire. When the client starts talking to the server and gets the decryptor out of order, some logic in packet_distribution.cpp causes it to enter the codepath for AO1 compatbility, and nothing is really loaded correctly. This PR simply adds a check so that, if the server was doubleclicked, it doesn't send askchaa until after getting a PN back. This ensures the handshake happens in the correct order when doubleclicking. This does not fix the same issue occuring if the connect button is pressed before the player count shows up, however.

File: src/lobby.cpp [hunk 1]
```diff
@@ -441,8 +441,9 @@ void Lobby::on_server_list_clicked(QTreeWidgetItem *p_item, int column)
 // doubleclicked on an item in the serverlist so we'll connect right away
 void Lobby::on_server_list_doubleclicked(QTreeWidgetItem *p_item, int column)
 {
+  doubleclicked = true;
```
Comment (oldmud0) [inline src/lobby.cpp:444]: Can this never be reset to `false`?

Comment (scatterflower) [reply src/lobby.cpp:444]: i had assumed the lobby object was destroyed when connecting to a server. given ao2 jank, i guess that isn't the case then...

Comment (scatterflower) [reply src/lobby.cpp:444]: regardless, the "doubleclicked = true" codepath doesn't seem to execute if you join a server and then return back to the lobby

File: src/packet_distribution.cpp [hunk 2]
```diff
@@ -228,6 +228,9 @@ void AOApplication::server_packet_received(AOPacket *p_packet)
 
     w_lobby->set_player_count(f_contents.at(0).toInt(),
                               f_contents.at(1).toInt());
+
+    if (w_lobby->doubleclicked)
+        send_server_packet(new AOPacket("askchaa#%"));
   }
```
Comment (stonedDiscord) [inline src/packet_distribution.cpp:234]: how about resetting it here

**Review by oldmud0 — APPROVED** [review]
e

**Review by stonedDiscord — APPROVED** [review]
nice
