### PR TITLE
Don't decode LE contents until after splitting by "&"

### LINKED ISSUE #492: Evidence name, filename, and description are not properly encoded before they are sent
**Describe the bug**
Evidence name, filename, and description are not properly encoded before they are sent. This affects all characters used in FantaProtocol, including `#`, `%`, and `&`.

**To reproduce**
1. Create a new piece of evidence
2. Change the name to "1&2&3"
3. Save the evidence
4. See error: Name is "1", filename is "2", and description is "3"

**Expected behavior**
Name should be set to "1&2&3," with other fields unaffected

**Version:**
 - Version or branch: 2.9.0

### PR DESCRIPTION
**Pull request by in1tiate**
this is probably a bad way of doing this but it does work

fixes #492

### CODE REVIEW

File: src/packet_distribution.cpp [hunk 1]
```diff
@@ -540,12 +541,19 @@ void AOApplication::server_packet_received(AOPacket *p_packet)
...
         if (sub_contents.size() < 3)
           continue;
 
+        // decoding has to be done here instead of on reception
+        // because this packet uses & as a delimiter for some reason
+        sub_contents.replaceInStrings("<num>", "#")
+                    .replaceInStrings("<percent>", "%")
+                    .replaceInStrings("<dollar>", "$")
+                    .replaceInStrings("<and>", "&");
+
```
Comment (oldmud0) [inline src/packet_distribution.cpp:556]: Please use the existing function.
```suggestion
        AOPacket::escape(sub_contents);
```

File: src/packet_distribution.cpp [hunk 2]
```diff
@@ -723,9 +731,7 @@ void AOApplication::send_server_packet(AOPacket *p_packet, bool encoded)
 
   QString f_packet = p_packet->to_string();
 
-#ifdef DEBUG_NETWORK
     qDebug() << "S:" << f_packet;
-#endif
```
Comment (oldmud0) [inline src/packet_distribution.cpp:728]: Weewoo debug police is here

**Review by oldmud0 — CHANGES_REQUESTED** [review]

**Review by oldmud0 — APPROVED** [review]
