### PR TITLE
Send "CC" packet when selecting "Spectator" from the character selection screen

### LINKED ISSUE #510: Demo server does not send guide message if player selects Spectator
**To reproduce**
1. Load a demo and connect to the demo server
2. When prompted to choose a character, click the "spectator" button
3. When the courtroom loads, OOC will be empty.

**Expected behavior**
An OOC message explaining how to start demo playback should appear.

### PR DESCRIPTION
**Pull request by in1tiate**
Fixes #510, and doesn't break anything as far as I can tell.

### CODE REVIEW

File: src/charselect.cpp [hunk 1]
```diff
@@ -168,7 +168,7 @@ void Courtroom::char_clicked(int n_char)
     }
   }
 
-  if (n_char != m_cid) {
+  if (n_char != m_cid || n_char == -1) {
```
Comment (oldmud0) [inline src/charselect.cpp:171]: I don't believe this will work on all servers because not all servers recognize CID -1, or if they do they won't answer with anything.

File: src/charselect.cpp [hunk 2]
```diff
@@ -174,6 +174,11 @@ void Courtroom::char_clicked(int n_char)
     ao_app->send_server_packet(
         new AOPacket("CC#" + QString::number(ao_app->s_pv) + "#" +
                      QString::number(n_char) + "#" + get_hdid() + "#%"));
+    if (n_char == -1) {
+      update_character(n_char);
+      enter_courtroom();
+      set_courtroom_size();
+    }
```
Comment (oldmud0) [inline src/charselect.cpp:181]: Bruh you did not need to do that

```cpp
  if (n_char != m_cid || n_char == -1) {
    ao_app->send_server_packet(
        new AOPacket("PW#" + ui_char_password->text() + "#%"));
    ao_app->send_server_packet(
        new AOPacket("CC#" + QString::number(ao_app->s_pv) + "#" +
                     QString::number(n_char) + "#" + get_hdid() + "#%"));
  }

  if (n_char == m_cid || n_char == -1) {
    update_character(n_char);
    enter_courtroom();
    set_courtroom_size();
  }
```

**Review by oldmud0 — CHANGES_REQUESTED** [review]

File: src/charselect.cpp (hunk 2 above)
Comment (in1tiate) [reply src/charselect.cpp:181]: you're right im sorry i have terminal dumb bitch disease its incurable

**Review by stonedDiscord — APPROVED** [review]
👌 🙆

**Review by oldmud0 — APPROVED** [review]
