### PR TITLE
Fix iniswap removal button disappearing on clicking 'reload theme'

### LINKED ISSUE #293: Reloading theme makes "X" buttons on iniswaps dropdown vanish.
Not sure what specifically causes this behavior, but to reproduce: Have anything but the default selected on the iniswaps dropdown, then reload theme. The X to delete that particular iniswap will vanish.

No idea what could be done to fix it as I'm not overly familiar with how reloading theme works.

### PR DESCRIPTION
**Pull request by in1tiate**
Fixes #293

### CODE REVIEW

File: src/courtroom.cpp [hunk 1]
```diff
@@ -705,6 +710,8 @@ void Courtroom::set_widgets()
          "the original character folder."));
   ui_sfx_remove->hide();
 
+  set_iniswap_dropdown();
```
Comment (Crystalwarrior) [inline src/courtroom.cpp:713]: ya

**Review by Crystalwarrior — APPROVED** [review]

**Review by oldmud0 — APPROVED** [review]
Again the style fixes should really belong in another commit. but okay.
