### PR TITLE
Audio fixes

### LINKED ISSUE #257: Program does not correctly handle changing audio devices during runtime [Bass Audio]
> when you have headphones on, and remove the headphones the music is muted
> Or how if you put in headphones the audio of ao will come through speakers anyway.

Basically, if the audio devices change after startup in any way, AO2 will not react or care in any way despite BASS providing relevant hooks for just that happening.

Fix this due to 2.8.5 and we will make a lot of returning old users very happy.

### LINKED ISSUE #263: Qt audio backend is broken on Linux
The Linux release did not really undergo a whole lot of testing, and it suffered likewise.

After I fixed the CI, the Linux version would simply crash upon joining a server due to the Qt Multimedia backend not exhibiting the same behavior as the BASS backend that was changed in 2.8. So I fixed that, but then there were more problems yet:

- Opus sound effects/blips can't be loaded with `QSoundEffect` because [`QSoundEffect` only supports WAV](https://code.woboq.org/qt5/qtmultimedia/src/multimedia/audio/qsoundeffect_pulse_p.cpp.html#_ZN19QSoundEffectPrivate18supportedMimeTypesEv). So we have to change blips to WAV, and make other SFX use the regular audio player instead.
- A-B loop support was never written.
- Other functionality implemented relies on calls to BASS-exclusive functions that don't have a 1:1 match with Qt Multimedia.

There are only two real options here:

1. Keep pushing through with Qt Multimedia, for the sake of open-source, since BASS is our only nonfree dependency.
2. Abandon Qt Multimedia, and start using BASS as the exclusive audio engine again.

### PR DESCRIPTION
**Pull request by scatterflower**
-  [x] Fixes #257
-  [x] Fixes #263

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Switching audio devices using the audio tab works
However, if I pulled out my headphones and put them in again, the client doesn't seem to switch to the new device unless I tell it to.

At the very least there's a way to make it work by using the audio tab, though an automatic solution would be preferred

**Review by Crystalwarrior — APPROVED** [review]

File: src/lobby.cpp [hunk 1]
```diff
@@ -353,13 +355,7 @@ void Lobby::on_connect_released()
...
 void Lobby::on_about_clicked()
 {
-#ifdef BASSAUDIO
-  const QString audio = "BASS";
-#elif defined(QTAUDIO)
-  const QString audio = "Qt Multimedia";
-#else
-  const QString audio = "null";
-#endif
+  const bool hasApng = QImageReader::supportedImageFormats().contains("APNG");
```
Comment (scatterflower) [inline src/lobby.cpp:358]: this is a good idea
