### PR TITLE
Handle packet decoding separately for SC packet

### LINKED ISSUE #430: Escaped Characters cutting Character Names in Character Select
**Describe the bug**
[I was working on an issue related to TSU](https://github.com/AttorneyOnline/tsuserver3/issues/124) and noticed that even sending the client a list of characters with escape characters properly handled, it is being presented improperly. 
I am under the assumption that the `SC` packet is what the client uses to display information

**To reproduce**
1. Download TSU's Master Branch
2. In the characters.yaml file, put an & in any of the characters names
3. In TSU edit 'aoprotocol.py' `net_cmd_rc` method to be
```py
    def net_cmd_rc(self, _):
        """Asks for the whole character list (AO2)

        AC#%

        """
        escaped_character_list = self.server.char_list
        for index, character in enumerate(escaped_character_list):
            character: str
            if '&' in character:
                escaped_character_name = character.replace('&', '<and>')
                escaped_character_list[index] = escaped_character_name
        print(escaped_character_list)
        self.client.send_command('SC', *escaped_character_list)
```
4. Connect to local TSU and see that the name is still cutoff

**Expected behavior**
The character information should still appear even if there's an escape code in the name.

**Screenshots**
image
image

**Version:**
 - OS: Windows 10
 - Version: 2.8.5

**Additional context**
Here's an output of the list that I send to the client with the escaped character 
`['Adrian', 'Apollo', 'April', 'Armstrong', 'Atmey', 'Butz', 'Diego', 'Edge<and>worth', 'Edgeworthw', 'Ema', 'EmaSkye', 'Franny', 'Franziska', 'Gant', 'Gavin', 'Gavin K', 'Godot', 'Gregory', 'Grossberg', 'Gumshoe', 'Gumshoey', 'Hawk', 'Hobo_Phoenix', 'Ini', 'Judge', "Judge's Bro", 'Klav', 'Klavier', 'Kristoph', 'Lana', 'Layton', 'Lotta', 'Luis', 'Maggey', 'Manfred', 'Marshall', 'Matt', 'Maya', 'Mia', 'Miles', 'Oldbag', 'Payne', 'Pearl', 'Phoenix', 'Valant', 'Vasquez', 'Wellington', 'Winston', 'WinstonPayne', 'Young Mia', 'Zak']`

### PR DESCRIPTION
**Pull request by skyedeving**
Theoretically fixes #430 

The bad behaviour comes from these two lines:

https://github.com/AttorneyOnline/AO2-Client/blob/c13e6b7ab0fd36ebf784294b2788ae365109a24f/src/packet_distribution.cpp#L11

https://github.com/AttorneyOnline/AO2-Client/blob/c13e6b7ab0fd36ebf784294b2788ae365109a24f/src/packet_distribution.cpp#L334

At the start the received packets are decoded by converting escaped chars to the actual ones. The issue is that ampersand characters are also used as the split token for the received character list. Fix will have to be making an exception for the packet.

### CODE REVIEW

File: src/packet_distribution.cpp [hunk 1]
```diff
@@ -333,6 +336,11 @@ void AOApplication::server_packet_received(AOPacket *p_packet)
     for (int n_element = 0; n_element < f_contents.size(); ++n_element) {
       QStringList sub_elements = f_contents.at(n_element).split("&");
 
+      sub_elements.replaceInStrings("#", "<num>")
+        .replaceInStrings("%", "<percent>")
+        .replaceInStrings("$", "<dollar>")
+        .replaceInStrings("&", "<and>");
+
```
Comment (stonedDiscord) [inline src/packet_distribution.cpp:343]: we have a function for this

**Review by stonedDiscord — CHANGES_REQUESTED** [review]

File: src/packet_distribution.cpp (hunk 1 above)
Comment (skyedeving) [reply src/packet_distribution.cpp:340]: It was kinda tied to the AOPacket class. I made new commits that should handle this with static functions.

**Review by oldmud0 — APPROVED** [review]

**Review by stonedDiscord — APPROVED** [review]
