### PR TITLE
Fix evidence not being consistently presentable

### LINKED ISSUE #1047: Evidence present animation doesn't play sometimes
Seems to be related to https://github.com/AttorneyOnline/AO2-Client/pull/1021. Oops.

### PR DESCRIPTION
**Pull request by Salanto**
closes #1047

### CODE REVIEW

File: src/courtroom.cpp [hunk 1]
```diff
@@ -3393,9 +3393,13 @@ void Courtroom::display_evidence_image()
     QString f_image = local_evidence_list.at(f_evi_id - 1).image;
     // QString f_evi_name = local_evidence_list.at(f_evi_id - 1).name;
     //  def jud and hlp should display the evidence icon on the RIGHT side
-    bool is_left_side = !(side.startsWith("def") || side == "hlp");
+    bool is_left_side = !(side.startsWith("def") || side == "hlp"); // FIXME : Hardcoded
```
Comment (in1tiate) [inline src/courtroom.cpp:3396]: doom#%

**Review by in1tiate — APPROVED** [review]
Looks fine to me
