### PR TITLE
Fix timestamps when toggling showname

### LINKED ISSUE #328: Toggling shownames sets visible log timestamps to current time
Toggling shownames on or off while log timestamps are enabled sets all visible* timestamps to the user's current time. Can be reproduced indefinitely.

*Appears to have no effect on timestamps in log _files_, only the in-game IC log.

### PR DESCRIPTION
**Pull request by skyedeving**
Fixes #328 

On toggling shownames, regenerate_ic_chatlog() gets called to reprint
the entire chatlog with append_ic_text().  The issue is that
append_ic_text() uses QDateTime::currentDateTime() for the timestamp
when it's called.  Therefore the fix is adding a new timestamp
parameter to the append_ic_text() which we supply from the datetime
provided by each chatlogpiece

### CODE REVIEW

File: src/courtroom.cpp [hunk 1]
```diff
@@ -2645,10 +2645,15 @@ void Courtroom::append_ic_text(QString p_text, QString p_name, QString p_action,
...
-    ui_ic_chatlog->textCursor().insertText(
-        "[" + QDateTime::currentDateTime().toString("h:mm:ss AP") + "] ",
-        normal);
+  if (log_timestamp) {
+    if (timestamp.isValid()) {
+      ui_ic_chatlog->textCursor().insertText(
+        "[" + timestamp.toString("h:mm:ss AP") + "] ", normal);
+    } else {
+      ui_ic_chatlog->textCursor().insertText(
+        "[" + QDateTime::currentDateTime().toString("h:mm:ss AP") + "] ", normal);
```
Comment (oldmud0) [inline src/courtroom.cpp:2654]: If the timestamp isn't valid, I'd rather not have any timestamp included.

Comment (skyedeving) [reply src/courtroom.cpp]: This was to take care of  behaviour when a timestamp wasn't provided so it'll still be displayed before regenerate_ic_text() is called. The default parameter value can be changed to call a function although.

**Review by oldmud0 — APPROVED** [review]
Yeah, this makes more sense now.
