### PR TITLE
Fix segfault in server list without a server selection 

### LINKED ISSUE #373: Click ADD TO FAV on startup to receive segmentation fault
1. Launch client
2. Click 'ADD TO FAV'
3. Receive segmentation fault

### PR DESCRIPTION
**Pull request by skyedeving**
Fixes #373 for most situations

Should take care of most situations, however it's still technically possible to segfault if the list isn't populated fast enough and it's still possible to segfault after unselecting the server with ctrl+click. These are specific situations though which are less likely to be encountered in the wild.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
holy shit, you're awesome

**Review by Iamgoofball — DISMISSED** [review]

**Review by oldmud0 — CHANGES_REQUESTED** [review]
I don't like this solution. It's hacky and doesn't solve the cases you mentioned. What you should do is modify `get_selected_server()` to return `-1` when there is no selected server, and then check for `-1` in all uses of `get_selected_server()`.

**Comment by skyedeving** [comment]
Fixed, agreed it was kinda hacky. Also, I'd like to bump up to c++17 if possible. c++20 would've been preferred but might be too new to have been widely distributed

File: src/lobby.cpp [hunk 1]
```diff
@@ -283,7 +283,10 @@ QString Lobby::get_chatlog()
 
 int Lobby::get_selected_server()
 {
-  return ui_server_list->currentItem()->text(0).toInt();
+  if (auto item = ui_server_list->currentItem()) {
+    return item->text(0).toInt();
```
Comment (oldmud0) [inline src/lobby.cpp:287]: What is the `0` argument? Looks to be an extraneous argument.

File: src/lobby.cpp [hunk 2]
```diff
@@ -333,12 +336,11 @@ void Lobby::on_add_to_fav_pressed()
...
 {
   ui_add_to_fav->set_image("addtofav");
-
-  // you cant add favorites from favorites m8
-  if (!public_servers_selected)
-    return;
-
-  ao_app->add_favorite_server(get_selected_server());
+  if (public_servers_selected) {
+    if (int selection = get_selected_server(); selection > -1) {
```
Comment (oldmud0) [inline src/lobby.cpp:340]: Put declarations on a different line than the if-statement if the comparison is more than a simple null check, please.

**Review by oldmud0 — CHANGES_REQUESTED** [review]

File: src/lobby.cpp (hunk 2 above)
Comment (skyedeving) [reply src/lobby.cpp:340]: It's a new feature part of C++17 https://en.cppreference.com/w/cpp/language/if

I don't mind moving out the declaration, just want one more comment as confirmation. I assume for readability/style.

File: src/lobby.cpp (hunk 1 above)
Comment (skyedeving) [reply src/lobby.cpp:287]: No idea, it probably is extraneous for us. Docs say it's the column: https://doc.qt.io/qt-5/qtreewidgetitem.html#text

File: src/lobby.cpp (hunk 2 above)
Comment (oldmud0) [reply src/lobby.cpp:340]: Yes, it's for readability.

File: src/lobby.cpp (hunk 1 above)
Comment (oldmud0) [reply src/lobby.cpp:287]: Oh, it's a tree widget, not a list widget. Intuitive AO2 code as usual.

**Review by Crystalwarrior — APPROVED** [review]

**Review by Iamgoofball — APPROVED** [review]

**Comment by Iamgoofball** [comment]
we have like 5 devs id be down for c++20
