### PR TITLE
Fix non-image files being loaded as images, fix custom shout button appearing on characters without it enabled

### LINKED ISSUE #592: Custom Shout Crash & Odd Behaviour
**Describe the bug**
Custom shout displays on characters that lack it showing the custom button, and crashes with characters that do have a custom shout.

**To reproduce**
Steps to reproduce the behaviour for custom shout button shout:
1. Select a character who does not have a custom shout
2. See custom shout button visible
3. Try to use custom shout
4. See custom shout button on screen

Steps to reproduce the behaviour for game crash:
1. Select a character who does have a custom shout
2. See custom shout button visible (as it should be)
3. Try to use custom shout
4. Game stops responding

**Expected behaviour**
Expected is custom shouts to not crash the game, and for the button to not display for those who do not have a custom shout (unless that got changed), nor for them to be able to display the custom shout button as a shout in the viewport.

**Screenshots**
bruhthur moment
blackquill when the

**Version:**
 - OS: Windows 10
 - Version or branch: current master

**Additional context**
ignore the theme

### PR DESCRIPTION
**Pull request by in1tiate**
Fixes #592

### CODE REVIEW

File: src/text_file_functions.cpp [hunk 1]
```diff
@@ -517,7 +517,7 @@ QString AOApplication::get_sfx_suffix(VPath sound_to_check)
 
 QString AOApplication::get_image_suffix(VPath path_to_check, bool static_image)
 {
-  QStringList suffixes { "" };
+  QStringList suffixes {};
```
Comment (oldmud0) [inline src/text_file_functions.cpp:520]: I am a bit concerned that there is some old logic somewhere that uses hardcoded extensions and removing the empty suffix will break it. I suspect that it was caused by failing to check whether a file is not a directory, on top of checking if the file exists. Regardless, if you think that this doesn't cause any regressions, I'll merge it.

**Review by oldmud0 — APPROVED** [review]

File: src/text_file_functions.cpp (hunk 1 above)
Comment (in1tiate) [reply src/text_file_functions.cpp:520]: I have a tester currently using this change as a 'daily driver' of sorts. It's not ideal but it should help catch any obvious regressions at the very least.

Comment (in1tiate) [reply src/text_file_functions.cpp:520]: Also - the empty string here actually renders the image suffix checker completely useless, since the code checks the ending of the path it gets from the cache against the suffixes list, and literally any call to `QString::endsWith("")` will return `true`. I removed an identical empty string from the audio suffix checker in https://github.com/AttorneyOnline/AO2-Client/pull/571, but evidently neglected to remove it from here as well.
